### PR TITLE
Fix #2 Getting Error for "useMediaQuery" being called in loop.

### LINKED ISSUE #2: Getting Error for "useMediaQuery" being called in loop.
React Hook "useMediaQuery" may be executed more than once. Possibly because it is called in a loop. React Hooks must be called in the exact same order in every component render

@ashutosh1919 , please assign this to me.

### PR DESCRIPTION
**Pull request by Sachin-chaurasiya**
Fixes #2 
This PR will include the following changes
- Adding types package for `react-responsive` 
- Fixing Hook being called in loop issue.

cc: @ashutosh1919

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@Sachin-chaurasiya, please follow the comment on the issue. We want to eliminate `react-responsive`. So, you may want to work in that direction. Also, there are couple of things that should be done before we can merge this PR.

1. Adding pre-commit to format all JS files for indentation.
2. Deploying website and creating deploy preview for the website.

Do not include code for these in this PR. If you want to work on this, then please create issue and I will assign it to you. Otherwise I anyway will work on this in early next week.

**Comment by Sachin-chaurasiya** [comment]
@Sachin-chaurasiya , I am clear with the first point and I'll create the issue for it.
On the second point can you please elaborate more.

**Comment by ashutosh1919** [comment]
@Sachin-chaurasiya you can carry on with the first one. I have to do second one since I have the write permission. Essentially, whenever a new PR is raised, we don't want to fetch it in local and see how does it look in UI. That is why we setup deploy previews. Whenever PR is raised, it will build UI and deploy it. So, we can directly see the UI changes in browser. You can read more about it [here](https://www.netlify.com/products/deploy-previews/). Don't worry. I will take care of this.

**Comment by Sachin-chaurasiya** [comment]
@ashutosh1919 , got it . I used this same approach in my portfolio project.

**Comment by ashutosh1919** [comment]
@Sachin-chaurasiya please consider synching this PR branch with current main to resolve merge conflicts

**Comment by Sachin-chaurasiya** [comment]
Closing this PR as lost track of it. Will raise ned PR for the same.

**Pull request closed without merging**
