### PR TITLE
Feat : added square & diamond shape

### PR DESCRIPTION
**Pull request by mohittk**
latest PR in response to #10 (closed) one.
Snapshot : 
image

### CODE REVIEW

**Comment by ashutosh1919** [comment]
@mohittk , there are only few formatting issues that you may want to fix: https://app.netlify.com/sites/awesomeshapes/deploys/62088a6aa604bac7f265bd6f

**Comment by ashutosh1919** [comment]
UI looks good to me. Looks fine in the mobile version too. In future when the website will be ready, we will improve mobile version further.

**Comment by ashutosh1919** [comment]
@all-contributors please add @mohittk for code,design and ideas

**Comment by mohittk** [comment]
> UI looks good to me. Looks fine in the mobile version too. In future when the website will be ready, we will improve mobile version further.

Yes! I saw it yesterday, it looked cool without any distortion.

**Comment by ashutosh1919** [comment]
https://github.com/all-contributors please add @mohittk for code and design

**Comment by ashutosh1919** [comment]
@all-contributors please add @mohittk for code and design

**Pull request merged**
